# Generated by Django 5.0.6 on 2024-05-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='simple_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
