# Generated by Django 5.0.6 on 2024-05-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_uploadedfile_simple_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='upload_complete',
            field=models.CharField(default='complete', max_length=100),
            preserve_default=False,
        ),
    ]
